{
 "title": "DigitalOcean Apps",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Live Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Apps Deployed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(digitalocean_app)" }
   ]
  },
  {
   "title": "Apps Currently Deploying",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(digitalocean_app{phase=\"DEPLOYING\"})"
    }
   ]
  },
  {
   "title": "Apps Currently Building",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(digitalocean_app{phase=\"BUILDING\"})"
    }
   ]
  },
  {
   "title": "Active App Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "digitalocean_app" }
   ]
  },
  { "title": "Historical Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Activated Apps (past 6 hours)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "count(count(digitalocean_app{phase=\"ACTIVE\"}) by (name))"
    }
   ]
  },
  {
   "title": "App Builds (past 6 hours)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(digitalocean_app{phase=\"BUILDING\"}[$__range]))"
    }
   ]
  },
  {
   "title": "App Deployments(past 6 hours)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(digitalocean_app{phase=\"DEPLOYING\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Deployment Activity",
   "type": "graph",
   "description": "Show when apps were deployed",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "digitalocean_app{phase=\"DEPLOYING\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}