{
 "title": "Broken Mcdonald's Ice Cream  Machines in the US",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Percentage Broken",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mcbroken{city=\"all\"}"
    }
   ]
  },
  {
   "title": "City with most broken",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "topk(1, mcbroken)", "legendFormat": "{{city}}" }
   ]
  },
  {
   "title": "Top broken city percentage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "topk(1, mcbroken)" }
   ]
  },
  {
   "title": "Percentage of broken Mcdonald's Ice Cream Machines",
   "type": "bargauge",
   "description": "Broken down by major US cities",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "mcbroken{}", "legendFormat": "{{city}}" }
   ]
  }
 ]
}